In [1]:
import tensorflow as tf;

In [3]:
rand = tf.random.uniform([1], 0, 1)

In [4]:
rand

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.23172212], dtype=float32)>

In [16]:
rand2 = tf.random.uniform([2, 2], 0, 1, dtype=tf.dtypes.float64)
rand2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.16683761, 0.69907497],
       [0.47256245, 0.1545962 ]])>

In [13]:
rand2.shape
rand2.dtype

tf.float64

In [18]:
rand3= tf.random.uniform([4], 0, 1)
rand3

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.46521723, 0.7441504 , 0.1558994 , 0.72263217], dtype=float32)>

# **뉴런만들기**

In [55]:
#[1] 활성화함수 만들기: sigmoid
#활성화함수: sigmoid, reLU

import math

def sigmoid(x):
    return 1 / (1 + math.exp(-x))

#[2] 뉴런의 입력과 출력 정의하기
#입력이 1일 때 기대출력이 0이 되는 뉴런: 
x = 1
y = 0

w = tf.random.normal([1], 0, 1)      #<------ 뉴런! 
output = sigmoid(x * w)

print(output)

#error 구하기
y_error = y - output

#[3]내가 원하는 값(y)이 나오도록 뉴런(가중치) 조절하기: 경사하강법(Gradient Descent)
#경사하강법: 가중치(w)에 (입력 * 학습률 * 에러)를 더해주는 것 
#  --손실곡선의 기울기. 손실곡선을 미분한 다음 그 값을 이용해서 가중치가 손실이 가장 낮아지는 지점에 도달하도록 반복 계산
for i in range(1000):
    output = sigmoid(x * w)
    error = y - output
    w = w + x * 0.1 * error     #학습률: 0.1
    
    if i % 100 == 99:
        print(i, error, output)

0.23857340368707922
99 -0.0778996460149631 0.0778996460149631
199 -0.0448869333993842 0.0448869333993842
299 -0.03132597136031582 0.03132597136031582
399 -0.02400272419246518 0.02400272419246518
499 -0.01943381797758382 0.01943381797758382
599 -0.016316546571690724 0.016316546571690724
699 -0.014056085032462926 0.014056085032462926
799 -0.012342882234992504 0.012342882234992504
899 -0.011000194241897012 0.011000194241897012
999 -0.009919826386252995 0.009919826386252995


In [56]:
#입력이 0일 때 기대출력이 1이 되는 뉴런:
x = 0
y = 1
w = tf.random.normal([1], 0, 1)

for i in range(1000):
    output = sigmoid(x * w)
    error = y - output
    w = w + x * 0.1 * error
    
    if i % 100 == 99:
        print(i, error, output)
        
#[!] 결과값이 같다: 0을 곱하기 때문에 w가 변하지 않는다. 
# =한 값만 나온다.
# =편향된 값만 나온다. 
#-----> 편향된 값만 나오는 것을 방지하기 위해 '편향(bias)'를 뉴런에 적용시킨다. 

99 0.5 0.5
199 0.5 0.5
299 0.5 0.5
399 0.5 0.5
499 0.5 0.5
599 0.5 0.5
699 0.5 0.5
799 0.5 0.5
899 0.5 0.5
999 0.5 0.5


In [61]:
#입력이 0일 때 기대출력이 1이 되는 뉴런의 학습에 편향 더하기:
x = 0
y = 1
w = tf.random.normal([1], 0, 1)
b = tf.random.normal([1], 0, 1)    #편향으로는 보편적으로 1을 사용한다. 

for i in range(1000):
    output = sigmoid(x * w + 1 * b)
    error = y - output
    w = w + x * 0.1 * error
    b = b + 1 * 0.1 * error
    
    if i % 100 == 99:
        print(i, error, output)

99 0.06817694475140834 0.9318230552485917
199 0.041382013786833594 0.9586179862131664
299 0.02955681863596271 0.9704431813640373
399 0.022943300087966523 0.9770566999120335
499 0.018730556031242518 0.9812694439687575
599 0.015816483631189593 0.9841835163688104
699 0.013682622608932493 0.9863173773910675
799 0.012053529668816676 0.9879464703311833
899 0.010769474503053544 0.9892305254969465
999 0.009731609195697044 0.990268390804303


# **첫 번째 신경망 네트워크: AND**

In [72]:
#두 개의 입력을 받는 AND 연산 
#입력값 두개가 모두 참일때만 참 반환

#cf. True, False로 어떤 수를 사용해야할까? (딥러닝의 주요 입력값은 int 또는 float!)
print('True는', int(True),
     'False는', int(False),
     '을 사용하자')

import numpy as np

x = np.array([[1, 1], [1, 0], [0, 1], [0, 0]])
y = np.array([[1], [0], [0], [0]])

w = tf.random.normal([2], 0, 1)
b = tf.random.normal([1], 0, 1)
b_x = 1

for i in range(2000):
    error_sum = 0
    for j in range(4):
        output = sigmoid(np.sum(x[j] * w) + b_x * b)
        error = y[j][0] - output
        w = w + x[j] * 0.1 * error
        b = b + b_x * 0.1 * error
        error_sum += error
        
    if i % 200 == 199:
        print(i, error_sum)
        
#AND 네트워크 평가하기
for i in range(4): 
    print('X:', x[i], 'Y:', y[i], 'Output:', sigmoid(np.sum(x[i]*w)+b))

True는 1 False는 0 을 사용하자
199 -0.1102554052535689
399 -0.06568725104315914
599 -0.04666688750070012
799 -0.036083767961627336
999 -0.029359903225083465
1199 -0.024719127242795937
1399 -0.021329000110601994
1599 -0.01874759790299529
1799 -0.016716244513070633
1999 -0.015077526523052213
X: [1 1] Y: [1] Output: 0.9647990349990229
X: [1 0] Y: [0] Output: 0.024944115643210082
X: [0 1] Y: [0] Output: 0.025020588159518495
X: [0 0] Y: [0] Output: 2.3952341757238866e-05


# **두 번째 신경망 네트워크: OR**

In [73]:
x = np.array([[1, 1], [1, 0], [0, 1], [0, 0]])
y = np.array([[1], [1], [1], [0]])

w = tf.random.normal([2], 0, 1)
b = tf.random.normal([1], 0, 1)
b_x = 1

for i in range(2000):
    error_sum = 0
    for j in range(4):
        output = sigmoid(np.sum(x[j] * w) + b_x * b)
        error = y[j][0] - output
        w = w + x[j] * 0.1 * error
        b = b + b_x * 0.1 * error
        error_sum += error
        
    if i % 200 == 199:
        print(i, error_sum)
        
#OR 네트워크 평가하기
for i in range(4): 
    print('X:', x[i], 'Y:', y[i], 'Output:', sigmoid(np.sum(x[i]*w)+b))

199 -0.04850842646722983
399 -0.025606662774803696
599 -0.017274601459725758
799 -0.012987975456363154
999 -0.010386948371658253
1199 -0.008645036212111247
1399 -0.007398823541600298
1599 -0.006463543131123399
1799 -0.0057370321790597804
1999 -0.005154939492648614
X: [1 1] Y: [1] Output: 0.9999971968883226
X: [1 0] Y: [1] Output: 0.989779481259482
X: [0 1] Y: [1] Output: 0.9897561660934151
X: [0 0] Y: [0] Output: 0.025558117303969473


# **세 번째 신경망 네트워크: XOR**

In [77]:
#XOR: 홀수개의 입력이 참일때만 결괏값이 참이된다
#입력값이 2개일 떄: 2개의 입력값이 다를 때 참이된다. 

x = np.array([[1, 1], [1, 0], [0, 1], [0, 0]])
y = np.array([[0], [1], [1], [0]])

w = tf.random.normal([2], 0, 1)
b = tf.random.normal([1], 0, 1)
b_x = 1

for i in range(2000):
    error_sum = 0
    for j in range(4):
        output = sigmoid(np.sum(x[j] * w) + b_x * b)
        error = y[j][0] - output
        w = w + x[j] * 0.1 * error
        b = b + b_x * 0.1 * error
        error_sum += error
        
    if i % 200 == 199:
        print(i, error_sum)
        
#XOR 네트워크 평가하기
for i in range(4): 
    print('X:', x[i], 'Y:', y[i], 'Output:', sigmoid(np.sum(x[i]*w)+b))
    
#[!]에러값이 변하다가 '어느 시점'부터 변하지 않는다: 
#output을 구성하는 w와 b 출력해보기: 
print('w:', w)    #----> 첫번째 입력이 두번째 입력보다 큰 영향
print('b:', b)    #----> 두번째 입력과 비슷하게 거의 영향이 없다
#네트워크가 어떤 일을 하려는지 불명확함. ==>여러 개의 퍼셉트론을 사용하자!

199 -0.009316108401358991
399 -0.0003789442627146755
599 -1.539763067615052e-05
799 -6.319523835340846e-07
999 1.1102230246251565e-16
1199 3.722842145670313e-09
1399 3.722842145670313e-09
1599 3.722842145670313e-09
1799 3.722842145670313e-09
1999 3.722842145670313e-09
X: [1 1] Y: [0] Output: 0.5128176286712095
X: [1 0] Y: [1] Output: 0.5128176305326305
X: [0 1] Y: [1] Output: 0.4999999990686774
X: [0 0] Y: [0] Output: 0.5000000009313226
w: tf.Tensor([ 5.1281754e-02 -7.4505806e-09], shape=(2,), dtype=float32)
b: tf.Tensor([3.7252903e-09], shape=(1,), dtype=float32)


In [80]:
#tf.keras를 이용한 XOR 네트워크 계산하기

x = np.array([[1, 1], [1, 0], [0, 1], [0, 0]])
y = np.array([[0], [1], [1], [0]])

model = tf.keras.Sequential([
    tf.keras.layers.Dense(units = 2, activation = 'sigmoid', input_shape = (2, )),
    tf.keras.layers.Dense(units = 1, activation = 'sigmoid')
])

model.compile(optimizer = tf.keras.optimizers.SGD(lr = 0.1), loss = 'mse')
#model: 딥러닝 계산을 위한 여러 함수와 변수의 묶음딥러닝을 계산하는 가장 핵심적인 단위
#tf.keras.Sequential: model에서 가장 많이 쓰이는 구조. 
#                     순차적으로 뉴런과 뉴런이 합쳐진 단위(레이어)를 일직선으로 배치하는 것.
#                     =시퀀셜 네트웤, 시퀀셜 모델
#                     인수: 레이어가 차례대로 정의된 리스트 전달
#tf.keras.layers.Dense: 레이어 정의 명령어. Dense는 가장 기본적인 레이어. 
#                       레이어 입출력 사이에 있는 모든 뉴런이 서로 연결되는 레이어. 
#                       units: 레이어를 구성하는 뉴런 수. cf.뉴런이 많을수록 레이어 성능 좋아지지만 메모리 UP
#                       input_shape: 시퀀셜모델의 첫번쩨 레이어에서만 정의.입력의 차원 수가 어떻게 되는지 정의.





model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 2)                 6         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 3         
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________
